### PR TITLE
[RELEASE] Bump to v5.4.0

### PR DESCRIPTION
**Pull request by sandrahoang686**
**HOLD until we merge https://github.com/NASA-IMPACT/veda-ui/pull/1073**

## 🎉 Features
* Added Announcement component using USWDS Design System and adding purge-css https://github.com/NASA-IMPACT/veda-ui/pull/1031

## 🚀 Improvements
* Add logic for tracking out-of-view Timeline playheads for E&A page https://github.com/NASA-IMPACT/veda-ui/pull/1067
* Abstract Away Faux Modules from MapBlock Component and expose as library component https://github.com/NASA-IMPACT/veda-ui/pull/1046

## 🐛 Fixes
- 🦗

### CODE REVIEW

**Review by hanbyul-here — APPROVED** [review]
Thanks for working on it 🙇  Can you add loading style fix as a bug fix ? https://github.com/NASA-IMPACT/veda-ui/pull/1073#pullrequestreview-2207605688

**Review by dzole0311 — APPROVED** [review]

**Comment by aboydnw** [comment]
I found an issue, I think this has to do with the playheads update and I didn't catch it when manually testing that ticket, sorry about that. But I don't think we can release this right now, the E&A page isn't really usable with more than one layer. Can somebody try and replicate this issue on their machine?

https://www.loom.com/share/9c0e468b5ee647d48dfd3a3d4c5a3d00?sid=830f9916-1e2f-47fb-bde8-eb0e831e0fb9

**Comment by aboydnw** [comment]
@hanbyul-here should the announcement text be centered? or is that just a formatting thing when configuring the banner?

**Comment by sandrahoang686** [comment]
Fix for Issue Anthony flagged has been addressed and merged https://github.com/NASA-IMPACT/veda-ui/pull/1077

**Comment by hanbyul-here** [comment]
@aboydnw It is not centered. I followed the banner style from uswds which is not centered: https://designsystem.digital.gov/components/banner/ 
In any case, I don't think it is worth blocking a release unless you think in a different way.

**Pull request merged**
