### PR TITLE
[FEATURE BRANCH] 902 E&A breakout

### PR DESCRIPTION
**Pull request by sandrahoang686**
**Related Ticket:** https://github.com/NASA-IMPACT/veda-ui/issues/902

### Description of Changes
**Related NextJs PR/Branch:** https://github.com/developmentseed/next-veda-ui/pull/4

**GHG Preview** with this branch pulled in generated here => https://github.com/US-GHG-Center/veda-config-ghg/pull/659

**Iteration 1** - Issue https://github.com/NASA-IMPACT/veda-ui/issues/902, changes by @sandrahoang686 
* Exposed `ExplorationAndAnalysis` component
* Exposed `timelineDatasetsAtom` to be used NextJs side
* Exposed & Moved/decoupled `DatasetSelectorModal` out of `ExplorationAndAnalysis`. ExplorationAndAnalysis only needs to know the dataset layers to be displayed. DatasetSelectorModal or whatever layer selection method should be controlled at the parent level above `ExplorationAndAnalysis`.
* Commented out certain controls that were breaking `ExplorationAndAnalysis` in NextJs instance 
   * `AnalysisMessageControl`
   * `CustomAoIControl`

### Notes & Questions About Changes
_{Add additonal notes and outstanding questions here related to changes in this pull request}_

### Validation / Testing
* Validate that Datalayer Selection Modal works as expected
* Validate that E&A features work as expected - aois, analyzation, adding/removing cards
* Validate that all card linking works as expected

### CODE REVIEW

**Comment by hanbyul-here** [comment]
🤚 I am having hard time running the branch on Next repo, getting an error from the line that uses `startOfYear` from `date-fns` `  > 91 |     .domain([startOfYear(now), endOfYear(now)])`  - Does anybody have an insights on what I should do?

**Comment by dzole0311** [comment]
> 🤚 I am having hard time running the branch on Next repo, getting an error from the line that uses `startOfYear` from `date-fns` ` > 91 | .domain([startOfYear(now), endOfYear(now)])` - Does anybody have insights on what I should do?

Yes, I had the same problem and fixed it in my map controls branch: https://github.com/NASA-IMPACT/veda-ui/pull/1205/files#diff-c01e76db4162d7ec2d29c4cd98dcadb5826d1ead020f96f94159a72d77d7b3b5R6

**Comment by sandrahoang686** [comment]
@hanbyul-here @dzole0311 yep, i highlighed that in an earlier PR - seems to be a known issue with parcel https://github.com/NASA-IMPACT/veda-ui/pull/1046#discussion_r1678578179

**Review by dzole0311 — APPROVED** [review]
Most of the changes were already tested via the other PRs, so I did a quick smoke test and couldn't spot anything blocking.

**Comment by sandrahoang686** [comment]
@hanbyul-here thanks for catching, created an issue for that [here](https://github.com/NASA-IMPACT/veda-ui/issues/1254) as i dont think its blocking 👍🏼

**Pull request merged**
