### PR TITLE
[Experiment] Vector source

### PR DESCRIPTION
**Pull request by danielfdsilva**
🛑🛑 DO NOT MERGE 🛑🛑

Quick experiment to see how vector data would work.
There are some hardcoded changes needed because the api is not fully finalized.

to view use this [preview](https://deploy-preview-481--veda-ui.netlify.app/covid-19/datasets/fire/explore?position=-103.6907|31.7749|9.36&datetime=2019-06-17T00%3A00%3A00.000Z)

### CODE REVIEW

**Comment by danielfdsilva** [comment]
The [api](https://pzh7fedpc0.execute-api.us-west-2.amazonaws.com/collections/public.eis_fire_fireline) is currently not working. @smohiudd Is there a new api?

**Comment by smohiudd** [comment]
@danielfdsilva sorry about. Here is the new api link: https://firenrt.delta-backend.com/collections/

**Comment by smohiudd** [comment]
Yes, you can try https://firenrt.delta-backend.com/collections/public.eis_fire_fireline/tiles/{z}/{x}/{y}

**Comment by danielfdsilva** [comment]
superseded by https://github.com/NASA-IMPACT/veda-ui/pull/496

**Pull request closed without merging**
