### PR TITLE
Update Staging Env Urls to point to New staging endpoints

### PR DESCRIPTION
**Pull request by sandrahoang686**
**Related Ticket:**  https://github.com/NASA-IMPACT/veda-ui/issues/1070
Related Slack [here](https://developmentseed.slack.com/archives/C045K5LAFA9/p1721849138598079) 

**We need to migrate to the new staging backend endpoints. Backend Docs with new endpoints [here](https://nasa-impact.github.io/veda-docs/services/apis.html)**

### Description of Changes
I noticed that some dataset layers in E&A were returning errors when trying to analyze in E&A page. And then saw this announcement in slack above. When switching to these, i no longer saw the errors.

Screenshot 2024-08-02 at 10 06 05 AM

### Notes & Questions About Changes
_{Add additonal notes and outstanding questions here related to changes in this pull request}_

### Validation / Testing
* **Manual Validation - check non ghg dataset/layers**

### CODE REVIEW

**Comment by sandrahoang686** [comment]
@anayeaye @smohiudd once this gets merged - https://github.com/NASA-IMPACT/veda-ui/pull/1075 will have the deploy preview where we can check that everything looks okay with the titler version update to endpoints. I checked locally though and it seemed fine 👍🏼

**Comment by hanbyul-here** [comment]
I see mosaic register failures for most of raster timeseries datasets (ex.no2: https://deploy-preview-1083--veda-ui.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22no2-monthly-2%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%2C%7B%22id%22%3A%22std%22%2C%22label%22%3A%22St+Deviation%22%2C%22chartLabel%22%3A%22St+Deviation%22%2C%22themeColor%22%3A%22infographicD%22%7D%5D%7D%7D%2C%7B%22id%22%3A%22no2-monthly%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22min%22%2C%22label%22%3A%22Min%22%2C%22chartLabel%22%3A%22Min%22%2C%22themeColor%22%3A%22infographicA%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%2C%7B%22id%22%3A%22max%22%2C%22label%22%3A%22Max%22%2C%22chartLabel%22%3A%22Max%22%2C%22themeColor%22%3A%22infographicC%22%2C%22style%22%3A%7B%22strokeDasharray%22%3A%222+2%22%7D%7D%5D%7D%7D%5D&taxonomy=%7B%7D&search=&date=2023-12-01T05%3A00%3A00.000Z&dateRange=)  Do you have more insights on this issue? @anayeaye ?

**Comment by smohiudd** [comment]
@hanbyul-here I believe you're still calling `https://staging.openveda.cloud/api/raster/mosaic/register` when it should be `searches/register`

**Comment by hanbyul-here** [comment]
Oh, I didn't know this service url is supposed to include the new titiler update. Then should this change go with https://github.com/NASA-IMPACT/veda-ui/pull/1075 not separately?

**Comment by smohiudd** [comment]
Yes titiler update got deployed to staging yesterday but we're waiting to deploy to production next week. All the endpoint changes should be included in #1075

**Comment by sandrahoang686** [comment]
Closing in favor of combining with https://github.com/NASA-IMPACT/veda-ui/pull/1075#event-13695405287

**Pull request closed without merging**
