### PR TITLE
[RELEASE] Bump minor to v5.11.0 

### PR DESCRIPTION
**Pull request by dzole0311**
### 🚀 Improvements
* Exploration & Analysis core VEDA feature breakout https://github.com/NASA-IMPACT/veda-ui/pull/1251 https://github.com/NASA-IMPACT/veda-ui/pull/1154
* Introduce `EnvConfigProvider` to simplify the injection of environment variables from host applications like Next.js https://github.com/NASA-IMPACT/veda-ui/pull/1253
* Remove React Router's `useNavigate` dependency for simplifying the routing https://github.com/NASA-IMPACT/veda-ui/pull/1270

### 🐛 Fixes
* Fix an issue where card images fail to maintain the correct aspect ratio https://github.com/NASA-IMPACT/veda-ui/pull/1265

### CODE REVIEW

**Review by sandrahoang686 — APPROVED** [review]

**Comment by aboydnw** [comment]
I spoke too soon. NO2 PT shows min/max. Any ideas why?
image

**Comment by hanbyul-here** [comment]
@aboydnw Editors can add their own metrics through `analysis.metrics` : https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/layer.md#analysis And NO2 PT data has min and max as its values: https://raw.githubusercontent.com/NASA-IMPACT/veda-ui/refs/heads/main/mock/datasets/no2.data.mdx  - Is this the problem you are observing? Or am I missing anything?

**Comment by aboydnw** [comment]
Ah okay, I didn't know that was possible. That was part of the question I called out in #1256 

so, maybe no problem, although I don't remember ever seeing these different chart types in previews before (I might have just missed it)

Do we think GHG and others know about this functionality?

**Comment by hanbyul-here** [comment]
I can't remember the exact concert but I believe it was the feature implemented by request (not sure if it was by GHG) so at least the people who requested this should know.

**Pull request merged**
