### PR TITLE
Change Discovery related strings to Data Stories

### PR DESCRIPTION
**Pull request by danielfdsilva**
@j08lue Could the preview url be used to show stakeholders?

### CODE REVIEW

**Comment by j08lue** [comment]
Great, yes, thank you!

Quick question: If we implemented this also in the URLs (and other naming behind the scenes) - could we keep a `/discoveries` alias for a while, so existing links elsewhere do not break?

**Comment by danielfdsilva** [comment]
@j08lue We would implement redirection for those paths, like we did for the thematic areas

**Comment by j08lue** [comment]
@danielfdsilva, we got confirmation that we should move ahead with this change. Can we deploy it to the GHG Center instance before July 14, still - perhaps just in this cosmetic version - and then work on the more thorough renaming?

**Review by j08lue — APPROVED** [review]
This is good for merging.

The title "Data Stories" is
* Right for GHG Center as far as we know
* Ok, although not ideal for NASA/EIS

Next steps after merging this:
1. Deploy for GHG
2. Deploy for NASA/EIS
3. Consider making the title configurable (see https://github.com/NASA-IMPACT/veda-ui/issues/574#issuecomment-1627197508)
4. Implement renaming in code/urls to use `stories`, if possible.

**Pull request merged**
