### PR TITLE
Add simplified US and Alaska

### PR DESCRIPTION
**Pull request by j08lue**
**Related Ticket:** #923 

### Description of Changes

Add back simplified versions of all-territories US and Alaska.

### Validation / Testing

Test analysis jobs with these regions

### CODE REVIEW

**Comment by j08lue** [comment]
Still not working but now I only need to remove a few smaller rings...

**Comment by j08lue** [comment]
Also filtered geometries do not work.

**Comment by j08lue** [comment]
The filtered and simplified geometries here seem to work, @hanbyul-here.

We could use these as last resort if we cannot make these work with the API.

**Comment by anayeaye** [comment]
We identified an AWS WAF size restriction associated with the GHG cloudfront that was causing everything > 16 KB to be rejected with 'exceeds size limit'. This can be adjusted up to a maximum 64 KB for more wiggle room. The geojson in this PR is small enough that it works without increasing that size limit on the GHG application firewall.

cc: @amarouane-ABDELHAK @smohiudd @botanical @j08lue @hanbyul-here

**Comment by j08lue** [comment]
Analysis of the original 1:20 million TIGER geometry now works, so we do not need to simplify geometries further. https://ghg-demo.netlify.app/exploration?datasets=%5B%7B%22id%22%3A%22micasa-co2-flux-npp-m%22%2C%22settings%22%3A%7B%22isVisible%22%3Atrue%2C%22opacity%22%3A100%2C%22analysisMetrics%22%3A%5B%7B%22id%22%3A%22mean%22%2C%22label%22%3A%22Average%22%2C%22chartLabel%22%3A%22Average%22%2C%22themeColor%22%3A%22infographicB%22%7D%5D%7D%7D%5D&date=2019-12-05T23%3A00%3A00.000Z&aois=%5B%22lbkcLmc%7EjGc%60D%7CuIvuFz%7EGt%7CIcdEu%7EB_xH%22%2C%2287260%22%2Ctrue%2C%22tulkLebd%7BFckUwb%40_%7BDebMcpKnlEiyCdlQ%60wIbeDz%7DN_QtjUop%40hoKq%60K%22%2C%2287261%22%2Ctrue%2C%22f%7BznLsfn%7BFgzLuwMwgOq_GgyHzvDwcJhnDiiE%7Eb%40i%60BjxKlfX%60%5BbuUpf%40btMpsFtgIhhIvjAazKnAycF%22%2C%2287262%22%2Ctrue%2C%22ja%7EsL%7DduzFqjHc%60%40yeAl%7BJ%7D%7BAnhEppMnS%60kFc%7EB%22%2C%2287263%22%2Ctrue%2C%22ne_vLgn_%7BFoz%40lqFd%7DUdfB%7DaBqtF%22%2C%2287264%22%2Ctrue%2C%22xd%7CnMm%60dgFiiDzeEn%5Bh%60LvaKu_B%7D%40s%60M%22%2C%2287265%22%2Ctrue%2C%22l%60%7EqNocnuCilNm%7EGkcPkgFasA%7ByBw%7CWicJi%60ZrjJkaKjzNniRlaF%60tJ%7CwAteGsvBhjM%7EdC%7Ew_%40%60fKpzWnqAgDmpC%22%2C%2287266%22%2Ctrue%2C%22lnksNg%7C_uC_oUoTlxHlxOtiTsBkqAgtG%22%2C%2287267%22%2Ctrue%2C%22rwjtNoahuCafJpiEdwAzaJzjNzVpt%40uyG%22%2C%2287268%22%2Ctrue%2C%22t%7BoxNq%7Es%7DFwkG%60sDne%40l%7DHrkI%60%7BAxcCqwK%22%2C%2287269%22%2Ctrue%2C%22zkzbOm%7BuvGwdRnrD_mKpmDrlFtsG%60rPgRneS%7DyM%60jKegI_wEk%7BE%22%2C%22872610%22%2Ctrue%2C%22d%7BwiOseevGk%7BWs%7CO%7B%7C%5EnkAbdBlnH%7CxXhu%60%40dfItvC%7C%7CJkuAhnMcvTz%5D_rF%22%2C%22872611%22%2Ctrue%2C%22tpdlOkfsrG%7BvIdt%40e%7CEteEzmCz%60JxlSpdMjiM%7BkAqgBa%7DF%22%2C%22872612%22%2Ctrue%2C%22lb_qOu%7EktGwyD%60hFtaK%7EtJ%7CgEvhJ%7C%7EIebJ_hCcoL%22%2C%22872613%22%2Ctrue%2C%22vxh_P%7DhqcHepm%40ooOakW%7BhFgdPswGyxQ_aHekg%40sdKxLhqGd%60W%60sKprDl%7EJdfZb%7CGxfYjyDz%7EG%7CrKfl%5BzwG%7EbUjeElrG%7DbDtlIs%60DurEyfE%22%2C%22872614%22%2Ctrue%2C%22buyhPuva%7EG_pPasBgnPjmBkcBtyB%7BnEz%7CIvlAz_Dp%7BCh%7DBbePpu%40ngGcsHrjEuuDv%7CIuiBxv%40ohC%22%2C%22872615%22%2Ctrue%2C%22%7CpdrUwokkEywe%40bqYrrFlfIptHebCfuPod%40vjBaqGdxN%7DqKx%7DDclE%22%2C%22872616%22%2Ctrue%2C%22ljorUyqhhEcfQjuO%7DeQdjMxaMndCfdK%7DqG%7EgQg_PlvJcuOehHstB%22%2C%22872617%22%2Ctrue%2C%22p%7BlxUmihjEwgOx%60G%7CMpkFvzErnAdzNioBtmEuyG%22%2C%22872618%22%2Ctrue%2C%22dspzUqp%7DnEm_VlhC%7Bv%60%40%7DXgfWkCiiN%7EScF%7ExHfqD%7Cc%40%7Ex%5E%7BRfdTpiAzkJlcD%60rM%7DSzbN_lBfUulGrtFuxE%22%2C%22872619%22%2Ctrue%2C%22nz%7B%7CUixznEkyShaEuwNwgAmyLboImaAbbG%7CyMnmDzaMxtBtdJwhEnbCusDtd_%40_yEbmP%7BaFswOkmH%22%2C%22872620%22%2Ctrue%2C%22dednVyufhHa%7CHkdCczFmxJ%7DbGyt%40yiVn%7CGevMncOv%7CIdeJwlD%60gGlp%40nmIlqFj%7BC%7DxArwIhxL%7C%60AtoIagCvuTe%7CBn%7ERazGn%7DJwqOlvE%7BeQ%22%2C%22872621%22%2Ctrue%2C%22viywVyhjfHkwlKt%7CyAz_g%40mneEo%7BzgDsfJajqa%40jg_EjouNplkFse_Y%7DuaCtdcCdsxB_emTtdNcz%60HfuvCpjaPdqI%7CvpHrweEkahDopfAj_qDzhbK%7DqyBxphIyy%7DD%7DevCy_F_baMooxFsy_EqvtHznoAl%7BlB%7CqkHy%7EeE%7Bg%60AoypAruvGj%7EtD%60z%60Dsr%7EDnnqAuygSkbeFshLmigCoshPobs%40exqFgzyGafiXseq%40ug%7CHqbqL_jvGjmkAe%60cD%7EbvLv%7B%7ETbbcH%7CuuAfmbEkvhE%60luCvnxShivAqbgHzoEnrtM%7E%7DmB%60%7DtBrapHxfbC%7BqdB%7Be%7EA%60cdEbomDj%7DhG%60rKwaeM%60q%7C%40tclGhlbEmbsA%7BasEf%7BoBenqCnxfNbima%40%7EqkU%60%7Cr%40p%60mGwmiGd%7EwTjfpE%7CpyK%7BvuBuqfBddhIyhxFtapBaovNhkqFsojEfntb%40feNig%60CiqXav%5DtmuDvvfJha%5EbxmRkcwBrp%7EPxhwItdgAf%7DrK%60ylIotkBlzcM%7BskSlhnJtsrCtscRu%7E%7BOppl%5Bp%7EpAts%7Cc%40_wiFrkoGmtbHbwyKuyeBfsyUqsya%40g%7D%7D%40gofc%40%22%2C%22872622%22%2Ctrue%5D&dateRange=2018-01-02T23%3A00%3A00.000Z%7C2020-02-05T23%3A00%3A00.000Z

**Pull request closed without merging**
