### PR TITLE
[Release] v5.9.0

### PR DESCRIPTION
**Pull request by hanbyul-here**
You can find VEDA Dashboard preview link to test these changes: https://github.com/NASA-IMPACT/veda-config/pull/470

## 🎉 Features
- Cookie consent component: https://github.com/NASA-IMPACT/veda-ui/pull/1163, https://github.com/NASA-IMPACT/veda-ui/pull/1165, https://github.com/NASA-IMPACT/veda-ui/pull/1127, https://github.com/NASA-IMPACT/veda-ui/pull/1177
- Stories Hub export  in https://github.com/NASA-IMPACT/veda-ui/pull/1162
- Expose As Is - PageHeader, LinkElement Prop & Logo in https://github.com/NASA-IMPACT/veda-ui/pull/1184
## 🚀 Improvements

- Add docs for registry dev in https://github.com/NASA-IMPACT/veda-ui/pull/1169
- Timeline date selection centering functionality in https://github.com/NASA-IMPACT/veda-ui/pull/1181
- Deprecate old explore page, Mapbox component https://github.com/NASA-IMPACT/veda-ui/pull/1176
- Update doc with new diagrams about general architecture in https://github.com/NASA-IMPACT/veda-ui/pull/1195
-  Add playwright in https://github.com/NASA-IMPACT/veda-ui/pull/1139
- Pre-select AOIs that have the "selected" prop set to true in https://github.com/NASA-IMPACT/veda-ui/pull/1215
- 
## 🐛 Fixes
- Check dastaset analysis exclude attribute before running analysis in https://github.com/NASA-IMPACT/veda-ui/pull/1175
- Restrict dynamic colormaps to applicable layer types in https://github.com/NASA-IMPACT/veda-ui/pull/1183
- Fix external link badge display for tools hosted under the same domain in https://github.com/NASA-IMPACT/veda-ui/pull/1192
- Escape special characters in regex expression when searching datasets  in https://github.com/NASA-IMPACT/veda-ui/pull/1204

### New Contributors
* @snmln made their first contribution in https://github.com/NASA-IMPACT/veda-ui/pull/1127
* @AliceR made their first contribution in https://github.com/NASA-IMPACT/veda-ui/pull/1204

### CODE REVIEW

**Review by snmln — APPROVED** [review]

**Comment by aboydnw** [comment]
@snmln for rescale values, some datasets show like this where the slider isn't functional. I can't tell what the common factor between them is, but I have noticed it on Difference CO2 and Gross Primary Productivity in the [preview](https://deploy-preview-470--visex.netlify.app/)
image

**Comment by sandrahoang686** [comment]
Rescale values get cut off when its a longer #, are we okay with that @aboydnw ?
https://github.com/user-attachments/assets/e5e8c518-6601-40b2-b9c4-50f42fb6cc33

**Comment by aboydnw** [comment]
Yeah I'm okay with that for now, I created a ticket to followup https://github.com/NASA-IMPACT/veda-ui/issues/1226

**Comment by aboydnw** [comment]
Okay I haven't found any other issues. The only thing I think we should look at is that rescale value issue @snmln , we should at least know why it's not working. Like is it something about the configuration of that dataset or something else? Ideally we'd fix it before releasing but maybe that depends on what the issue is and how tricky of a fix it is

**Comment by snmln** [comment]
@aboydnw I believe it is related to the dataset and the Min and Max points being `-.00000015` and `.00000015` so the original increment of `.001` that I had set based on the dev environment datasets. I believe would present in the error you are seeing. I am exploring a potential solution currently and will keep you posted if that will correct the problem.

**Comment by snmln** [comment]
@aboydnw I have a solution locally but need to validate with some more testing for the sake of not holding back the release I am going to remove the range slider from this release.

**Review by dzole0311 — APPROVED** [review]

**Pull request merged**
