### PR TITLE
Configurable metrics for analysis page

### PR DESCRIPTION
**Pull request by danielfdsilva**
Analysis metrics can now be selected on a chart basis.
image

The default metrics are configurable through the dataset mdx file under the `analysis.metrics` property of every layer.
image

Any invalid id id discarded.

@ricardoduplos Please have a quick design sanity check

### CODE REVIEW

**Comment by danielfdsilva** [comment]
This PR also includes an option to disable certain dataset layers to be selected for analysis (as described in https://github.com/NASA-IMPACT/veda-ui/issues/654)

**Review by nerik — APPROVED** [review]
Looks good to merge!

**Comment by j08lue** [comment]
> Looks good to merge!

Since @danielfdsilva is out, pls feel free to proceed, @nerik. Even in the current state, this is a good improvement to the existing UI, IMO.

**Comment by nerik** [comment]
Ok. Merging this @ricardoduplos, let me know if anything's need to be adressed.

**Pull request merged**
