### PR TITLE
Update titler-xarray-endpoint to production

### PR DESCRIPTION
**Pull request by abarciauskas-bgse**
There are now 2 deployments of titiler-xarray: one production endpoint and one dev. Dev will be reserved for new feature development and testing, so we should use the production endpoint in VEDA dashboard services. I will make an equivalent PR to veda-config.

### CODE REVIEW

**Comment by hanbyul-here** [comment]
While we are at it, I want to flag that the example data you put (`oco2-geos-l3-daily`) is missing spatial and temporal extent. which leads to the error on the page. (I noticed this issue a while ago, so I believe it is unrelated to changing the endpoint to production.)

- Are spatial and temporal extent intentionally missing?
- If so, is there a better example zarr data to put? since `oco2-geos-l3-daily` is missing the values that dashboard needs?

**Comment by abarciauskas-bgse** [comment]
@hanbyul-here thanks for looking, tagging @slesaad who published that dataset. @slesaad should we fix or remove this dataset? I can look into doing so if it would help.

**Comment by danielfdsilva** [comment]
@abarciauskas-bgse Should we change this in the veda-ui, given that this is never used directly? Wouldn't it make more sense to keep the dev endpoint here? Is it unstable?

**Comment by abarciauskas-bgse** [comment]
🤔 The intention to have dev and prod deployment is that dev might be unstable. I do think it could be useful to leave the configuration here pointing to dev so we can test new features' in titiler-xarray are still working with VEDA UI. So yes I think it makes sense to close this for now.

**Pull request closed without merging**
