### PR TITLE
Update analysis messages

### PR DESCRIPTION
**Pull request by danielfdsilva**
Closes https://github.com/NASA-IMPACT/veda-ui/issues/741

### CODE REVIEW

**Review by j08lue — CHANGES_REQUESTED** [review]
A few differences from the [designs](https://github.com/NASA-IMPACT/veda-ui/issues/741#issuecomment-1833607303):

## 1. The cases "one unselected dataset" and "multiple unselected datasets" 

Should be:

image

Is (in both cases):

image


## 2. Analysis tools label should be capitalized (is all caps) and separated by spacer

Should be:

image

Is:

image

## 3. "Selection changed" message is not vertically centered

Should be:

image

Is (slightly lower - you see it best when the message changes in the app):

image

**Comment by danielfdsilva** [comment]
@j08lue Addressed!

**Review by faustoperez — CHANGES_REQUESTED** [review]
Looking good Daniel!

Just one small thing: when an analysis is active, I think that deleting the shape should have the same effect as exiting the analysis. I.e. not getting the "Selection changed" message when deleting the shape, but making the two buttons behave the same.

I know that this changes a bit the current behaviour (not just a styling thing), what do y'all think?

image

**Review by j08lue — APPROVED** [review]
Thanks for addressing my review so thoroughly! The messaging and layout looks great and works as expected through different scenarios.

@faustoperez you suggested that we adjust the behavior towards deleting last shape = exit analysis. In the interest of getting this deployed for demo and further testing as soon as possible, I recommend that we keep that for later and observe more users throughout the refined flow and see how they deal with these steps of the flow.

So, if you are okay with that, @faustoperez, I'd say let us keep the flow as-is for now.

**Comment by faustoperez** [comment]
> So, if you are okay with that, @faustoperez, I'd say let us keep the flow as-is for now.

Sounds great Jonas!

**Pull request merged**
