### PR TITLE
Fix Y-axis label missing in the analysis page.

### PR DESCRIPTION
**Pull request by rajdangol0077**
Fixes https://github.com/NASA-IMPACT/veda-ui/issues/877

### CODE REVIEW

**Comment by slesaad** [comment]
@rajdangol0077 i see that there's still some issues, look at the attached images (datasets: NO2 PT and NPP)
image - the label and values are overlapping
image - the superscript 2 is cutoff a bit

Can you see if you can fix those too?

**Comment by rajdangol0077** [comment]
> @rajdangol0077 i see that there's still some issues, look at the attached images (datasets: NO2 PT and NPP) image - the label and values are overlapping image - the superscript 2 is cutoff a bit
> 
> Can you see if you can fix those too?

I could only fix this by adding width and offset to the axis and labels. Do verify and let me know if I need to make other changes.

**Comment by rajdangol0077** [comment]
@slesaad I could only fix this by adding width and offset to the axis and labels. Do verify and let me know if I need to make other changes.

**Review by sandrahoang686 — APPROVED** [review]
Manually validated analysis page results. lgtm!

**Pull request merged**
