### PR TITLE
Homepage content

### PR DESCRIPTION
**Pull request by danielfdsilva**
Updating homepage content based on feedback #338

cc @hanbyul-here @nerik @ricardoduplos

### CODE REVIEW

**Comment by danielfdsilva** [comment]
@michaelgsuttles @aboydnw If any further content updates are needed, comment directly on this PR. We'll include this in the next push.

**Comment by michaelgsuttles** [comment]
> @michaelgsuttles @aboydnw If any further content updates are needed, comment directly on this PR. We'll include this in the next push.

@danielfdsilva Thank you! The other small change I mentioned is the capitalization of "NASA is Keeping a watchful eye on our atmosphere"--change "Keeping"

**Comment by michaelgsuttles** [comment]
@danielfdsilva Not sure if you already did this, but pasting Brian's feedback here: 
"[...] it might be better to switch the thematic areas section with the VEDA serves a wide scientific audience section [...]"
cc: @aboydnw @ricardoduplos

**Comment by danielfdsilva** [comment]
@michaelgsuttles 
> @danielfdsilva Thank you! The other small change I mentioned is the capitalization of "NASA is Keeping a watchful eye on our atmosphere"--change "Keeping"

This is the description of a thematic area and should be updated on the `veda-config` repo. (https://github.com/NASA-IMPACT/veda-config/blob/develop/thematic/air-quality.thematic.mdx?plain=1)

**Comment by danielfdsilva** [comment]
@michaelgsuttles @aboydnw Thematic area list switched with Audience

**Review by ricardoduplos — APPROVED** [review]

**Pull request merged**
