### PR TITLE
chore: add playwright

### PR DESCRIPTION
**Pull request by stephenkilbourn**
**Related Ticket:** https://github.com/NASA-IMPACT/veda-ui/issues/1024 https://github.com/NASA-IMPACT/veda-ui/issues/1197

### Description of Changes
This adds Playwright tests of some key user flows.  The tests are set to run on the github action. On failure, an html report along with traces containing screenshots and network calls will be attached to the action's step.

The tests will run only on release branches (branches starting with `release`).

### Validation / Testing
tests can be run locally with `yarn test:e2e` and they can also be seen in the github action.

### CODE REVIEW

**Comment by stephenkilbourn** [comment]
It looks like I don't have access to view/change github secrets.  This is expecting a mapbox token stored as `MAPBOX_TOKEN` like in the veda-config.

**Comment by dzole0311** [comment]
Thanks @stephenkilbourn for the great work and getting the tests green! I'm considering adjusting the github job to run on release branches only instead of each feature branch, to keep the fast development lifecycle. @sandrahoang686 @AliceR @hanbyul-here @snmln – any opinions before we merge these?

**Review by dzole0311 — APPROVED** [review]

**Comment by sandrahoang686** [comment]
@stephenkilbourn thanks for setting this up, tests will be pretty crucial going forward and we could definitely spend more time here. Just a few thoughts -
* Do we want routing tests here? For those tests, we'd probably want at the instance level?
   * Path would eventually change to `await page.goto('/data-catalog');` for example this path would eventually come from instance
* At the instance level we orchesta e2d behavior so would we want to move more towards integration testing? 

cc @dzole0311 maybe you have more thought out thoughts here though

**Comment by stephenkilbourn** [comment]
@sandrahoang686 @dzole0311 

We do have existing tests at the instance level in [veda-config](https://github.com/NASA-IMPACT/veda-config/pull/363) and [GHG.](https://github.com/US-GHG-Center/veda-config-ghg/tree/develop/e2e) My intent was to move the common ones down to the UI level to remove duplication. We can then have tests against anything unique to that instance live in the config repos.

I can set up the routes to read from an env if you think that makes sense.  I can set in the playwright config to read from the env and default to the route that is in the current UI. 
something along the lines of 
```
const catalogRoute = process.env.CATALOG_ROUTE ? process.env.CATALOG_ROUTE : 'data-catalog`
await page.goto(catalogRoute);
```

**Comment by dzole0311** [comment]
@sandrahoang686 Yes I think we can move away from routing in the tests as we break out the components. But for consistency with our current architecture, I propose we keep it for now.

Since this PR provides a solid base for more extensive Playwright tests in the veda-ui, I’ll go ahead and merge it so we can start playing with them and using them into our dev workflow, and make modifications as needed. Thanks @stephenkilbourn for setting these up!

We have a follow-up here: https://github.com/NASA-IMPACT/veda-ui/issues/1200

**Pull request merged**
