### PR TITLE
Add 'skip to main' to navigation

### PR DESCRIPTION
**Pull request by hanbyul-here**
Add keyboard focusable 'Skip to main content' Button.
part of https://github.com/NASA-IMPACT/veda-ui/issues/807
Since we don't have an anchor link, We have to rely on some workaround (Manually focusing page body).

You should be able to see it by trying to keyboard navigate the page, but this is the screenshot.

Screen Shot 2024-01-22 at 12 21 03 PM

### CODE REVIEW

**Comment by faustoperez** [comment]
@hanbyul-here looking good!

In the preview it only works on the homepage, is that the intended behaviour? Thanks!

**Comment by hanbyul-here** [comment]
@faustoperez oh no it should work on every page. But, when the page changes, your focus stays on the element you interacted with. ex. I click on 'data catalog' from the home page, my next focusable element will be data analysis. If I navigate back (shift+tab), then I can get to the navigation. (This focusing behavior can be also confusing for screen reader users... but let's keep this pr in its scope for now.) Lmk if you could get it working in other pages! 

Screen Shot 2024-01-24 at 11 28 58 AM

**Comment by faustoperez** [comment]
gotcha, thanks for the clarification @hanbyul-here ! 🙌

**Review by faustoperez — APPROVED** [review]
Looking good, thanks for taking care of this!

**Pull request merged**
