### PR TITLE
Added retrieve previous settings feature

### PR DESCRIPTION
**Pull request by nerik**
🛑 Given this feature's dependency on functionalities from https://github.com/NASA-IMPACT/veda-ui/pull/438, it can only be merged after it.

----

Screenshot 2023-01-12 at 15 09 29

Adds very bare bone functionality for https://github.com/NASA-IMPACT/veda-ui/issues/385

Need to discuss:
- How to set up the Dropdown's `DropMenu` for long labels?
- Proper placement and labeling of this button
- Should this button also be present on the results page?
- Do we need to save previous settings __per thematic area__?
- Should we try to represent the AoI on the saved preset label?

### CODE REVIEW

**Comment by danielfdsilva** [comment]
- How to set up the Dropdown's DropMenu for long labels?
I imagine this would be something more complex than a drop menu, and I like the idea of showing the AOI. Perhaps something along the following. @ricardoduplos Can you help with designing this? Handling long names is definitely a concern. It should be clear, so not sure we can hide it behind ellipsis.


image

- Should this button also be present on the results page?
For quick access it may be a good idea. However, what would the behavior be? On click open the analysis immediately? On the define page it populates the different fields. cc @ricardoduplos 

- Do we need to save previous settings per thematic area?
Yes. Since the datasets depend on the thematic area, they may not be available in another.

**Review by ricardoduplos — APPROVED** [review]

**Comment by danielfdsilva** [comment]
QA Expected behavior:

From the analysis definition or results page it is possible to access the last 5 analysis. This list is specific to each thematic area, since each has its own analysis.
- Selecting a past analysis from the definition page prefills all the form elements
- Selecting a past analysis from the results page shows the analysis immediately

**Comment by karitotp** [comment]
This is working with expected behavior in all thematic areas!

> From the analysis definition or results page it is possible to access the last 5 analysis. This list is specific to each thematic area, since each has its own analysis.
> - Selecting a past analysis from the definition page prefills all the form elements
> - Selecting a past analysis from the results page shows the analysis immediately

**Review by danielfdsilva — APPROVED** [review]
Good to go after #438

**Pull request merged**
